## IRIS

### Typologie des IRIS

sources: [Insee](https://www.insee.fr/fr/metadonnees/definition/c1523), [geoconcept]
(https://fr.geoconcept.com/zone-iris)<br>
<br>
Les IRIS constituent chacun un « micro quartier », composé d'un ensemble **d'îlots contigus et homogènes**, regroupant **2000 habitants ou plus**.

Chaque IRIS constitue un secteur communal de base, un « micro quartier » géographique et démographique homogène, clairement et durablement defini. Sur ce « maillon élémentaire » est pratiquée la collecte de données statistiques et démographiques. Ces données sont ensuite analysées et les résultats publiés par l'INSEE.

La France compte 50 800 IRIS, dont 700 dans les DOM répartis comme suit :

- 16 100 IRIS, dont 650 dans les DOM, issus du découpage des communes de plus de 10 000 habitants, et la plupart des communes de 5 000 à 10 000 habitants,
- 34 800 IRIS, constitués par les communes non-découpées.


Les IRIS se déclinent en trois types de zones :

- **IRIS d'habitat (H)** : IRIS dont la population se situe entre 1 800 et 5 000 habitants ; ils sont homogènes quant au type d'habitat ;
- **IRIS d'activité (A)**: IRIS regroupant plus de 1 000 salariés et comptent deux fois plus d'emplois salariés que de population résidente ;
- **IRIS divers (D)**: IRIS de superficie importante à usage particulier (bois, parcs, zones portuaires...).
- **IRIS autres (Z)**.<br>
Plus de 92% des IRIS sont des IRIS d’habitat, 5% des IRIS d’activité.


### Code IRIS
À chaque îlot est associé un code IRIS. Composé de 9 caractères. Il permet d'identifier de manière univoque un îlot. Les cinq premiers caractères du code IRIS correspondent au code Insee de la commune sur le territoire de laquelle est situé l'îlot.

### Différentes bdd sur bases IRIS :
- Population 2016
- Couple, familles, ménages 2016
- Logements 2016
- Activités des résidents 2016
<br>
(Non pris en compte Diplômes et formation 2016.)

In [1]:
import pandas as pd
import numpy as np

## Ménage 2016 (IRIS) - France hors Mayotte
infra-communales

In [2]:
# Population hors ménages![image.png](attachment:image.png)
varmenIR = pd.read_excel('IRIS_household/variable_coupl-fam-mena-2016-cIA.xlsx')
varmenIR

,Données infra-communales - Couples - Familles - Ménages,Unnamed: 1,Unnamed: 2
0,Variables,NaN,NaN
1,Mise en ligne le 22/10/2019 Géographie a...,NaN,NaN
2,"©Insee Source(s) : Insee, Recensements d...",NaN,NaN
3,NaN,NaN,NaN
4,VAR_ID,VAR_LIB,VAR_LIB_LONG
...,...,...,...
72,C16_NE24F0,Fam 0 enfant moins 25 ans en 2016 (compl),Nombre de familles avec 0 enfant de moins de 2...
73,C16_NE24F1,Fam 1 enfant moins 25 ans en 2016 (compl),Nombre de familles avec 1 enfant de moins de 2...
74,C16_NE24F2,Fam 2 enfants moins 25 ans en 2016 (compl),Nombre de familles avec 2 enfants de moins de ...
75,C16_NE24F3,Fam 3 enfants moins 25 ans en 2016 (compl),Nombre de familles avec 3 enfants de moins de ...
76,C16_NE24F4P,Fam 4 enfants ou plus moins 25 ans en 2016 (co...,Nombre de familles avec 4 enfants ou plus de m...

In [3]:
menIR = pd.read_excel('IRIS_household/base-ic-couples-familles-menages-2016-cIA.xls')

In [4]:
menIR.head(10)

,IRIS,REG,DEP,UU2010,COM,LIBCOM,TRIRIS,GRD_QUART,LIBIRIS,TYP_IRIS,...,C16_PMEN_CS8,C16_FAM,C16_COUPAENF,C16_FAMMONO,C16_COUPSENF,C16_NE24F0,C16_NE24F1,C16_NE24F2,C16_NE24F3,C16_NE24F4P
0,010010000,84,01,01000,01001,L'Abergement-Clémenciat,ZZZZZZ,0100100,L'Abergement-Clémenciat (commune non irisée),Z,...,0.000000,235.000000,110.000000,15.000000,110.000000,115.000000,45.000000,60.000000,10.000000,5.000000
1,010020000,84,01,01000,01002,L'Abergement-de-Varey,ZZZZZZ,0100200,L'Abergement-de-Varey (commune non irisée),Z,...,0.000000,75.000000,35.000000,5.000000,35.000000,35.000000,10.000000,25.000000,0.000000,5.000000
2,010040101,84,01,01302,01004,Ambérieu-en-Bugey,ZZZZZZ,0100401,Les Perouses-Triangle d'Activité,H,...,127.247897,390.570446,158.868143,60.249920,171.452383,181.095310,106.089356,60.480764,20.029664,22.875352
3,010040102,84,01,01302,01004,Ambérieu-en-Bugey,ZZZZZZ,0100401,Longeray-Gare,H,...,242.400400,901.601094,380.516880,182.763722,338.320491,372.444379,225.771727,185.178437,95.096017,23.110533
4,010040201,84,01,01302,01004,Ambérieu-en-Bugey,ZZZZZZ,0100402,Centre-St Germain-Vareilles,H,...,100.170536,1074.047707,408.370964,235.021967,430.654777,467.844492,289.582304,166.339845,128.562648,21.718418
5,010040202,84,01,01302,01004,Ambérieu-en-Bugey,ZZZZZZ,0100402,Tiret-Les Allymes,H,...,58.822726,1373.103550,575.875935,182.868830,614.358784,658.834702,306.544973,282.242270,96.581413,28.900192
6,010050000,84,01,01000,01005,Ambérieux-en-Dombes,ZZZZZZ,0100500,Ambérieux-en-Dombes (commune non irisée),Z,...,5.220346,495.846734,252.036505,46.461075,197.349154,238.667090,92.920449,118.317132,35.761339,10.180724
7,010060000,84,01,01000,01006,Ambléon,ZZZZZZ,0100600,Ambléon (commune non irisée),Z,...,0.000000,35.000000,10.000000,5.000000,20.000000,20.000000,10.000000,5.000000,0.000000,0.000000
8,010070000,84,01,01000,01007,Ambronay,ZZZZZZ,0100700,Ambronay (commune non irisée),Z,...,41.807902,772.934636,365.438906,94.022501,313.473229,370.926269,146.239366,187.934122,62.619073,5.215807
9,010080000,84,01,01302,01008,Ambutrix,ZZZZZZ,0100800,Ambutrix (commune non irisée),Z,...,14.900662,218.543046,104.304636,24.834437,89.403974,99.337748,54.635762,54.635762,4.966887,4.966887

## Ménage
- IRIS MENAGE CSP<br>
**GEO** : IRIS / Libé commune ou ARM / Type d'IRIS<br>
**Pop Ménage** (Nb pers. ménage) :  1 pers. / Autres sans famille / Avec famille +<br>
**CSP Ménage**(Nb pers. ménage) : CS1 Agriculteur exploit. / CS2 Artisants, commerçants, Chef d'E. / CS3 Cadres Prof. Int. Sup. / CS4 Prof. Inter. / CS5 Employés / CS6 Ouvriers / CS7 Retraités / CS8 Autres sans activités pro.<br>
<br>
- IRIS MENAGE (DETAIL) CSP<br>
**GEO** : IRIS / Libé commune ou ARM / Type d'IRIS<br>
**Pop Ménage** (Nb pers. ménage) :  1 homme seul / 1 femme seul / Autres sans famille / Couple sans enfant / Couple avec enfant / Famille monoparentale<br>
**CSP Ménage**(Nb pers. ménage) : CS1 Agriculteur exploit. / CS2 Artisants, commerçants, Chef d'E. / CS3 Cadres Prof. Int. Sup. / CS4 Prof. Inter. / CS5 Employés / CS6 Ouvriers / CS7 Retraités / CS8 Autres sans activités pro.<br>

In [5]:
menIR_Wbase = menIR[['IRIS', 'REG', 'DEP', 'UU2010', 'COM','LIBCOM', 'GRD_QUART', 'LIBIRIS', 'TRIRIS', 'TYP_IRIS', 'MODIF_IRIS', 'LAB_IRIS',
                    'C16_PMEN_MENPSEUL', 'C16_PMEN_MENSFAM', 'C16_PMEN_MENFAM', 'C16_PMEN_MENHSEUL', 'C16_PMEN_MENFSEUL',
                    'C16_PMEN_MENCOUPSENF', 'C16_PMEN_MENCOUPAENF', 'C16_PMEN_MENFAMMONO', 'C16_PMEN_CS1', 'C16_PMEN_CS2', 'C16_PMEN_CS3',
                   'C16_PMEN_CS4', 'C16_PMEN_CS5', 'C16_PMEN_CS6', 'C16_PMEN_CS7', 'C16_PMEN_CS8']]

In [6]:
menIR_Wbase.apply(lambda x: len(x.unique()))

IRIS                    49637
REG                        17
DEP                       100
UU2010                   2373
COM                     35382
LIBCOM                  33042
GRD_QUART               37624
LIBIRIS                 43986
TRIRIS                   3483
TYP_IRIS                    4
MODIF_IRIS                  4
LAB_IRIS                    6
C16_PMEN_MENPSEUL       38760
C16_PMEN_MENSFAM        27023
C16_PMEN_MENFAM         40857
C16_PMEN_MENHSEUL       36983
C16_PMEN_MENFSEUL       37018
C16_PMEN_MENCOUPSENF    39193
C16_PMEN_MENCOUPAENF    40133
C16_PMEN_MENFAMMONO     35313
C16_PMEN_CS1            20045
C16_PMEN_CS2            34493
C16_PMEN_CS3            34603
C16_PMEN_CS4            38022
C16_PMEN_CS5            38158
C16_PMEN_CS6            38760
C16_PMEN_CS7            39622
C16_PMEN_CS8            29344
dtype: int64

In [14]:
menIR_new = menIR_Wbase.drop(columns=['REG', 'DEP', 'UU2010', 'COM', 'GRD_QUART', 'LIBIRIS','TRIRIS', 'MODIF_IRIS', 'LAB_IRIS',
                                'C16_PMEN_MENHSEUL', 'C16_PMEN_MENFSEUL', 'C16_PMEN_MENCOUPSENF', 'C16_PMEN_MENCOUPAENF',
                                'C16_PMEN_MENFAMMONO'])

menDetail_IR_new = menIR_Wbase.drop(columns=['REG', 'DEP', 'UU2010', 'COM', 'GRD_QUART', 'LIBIRIS','TRIRIS', 'MODIF_IRIS', 'LAB_IRIS',
                               'C16_PMEN_MENPSEUL', 'C16_PMEN_MENFAM'])

In [15]:
menIR_new.apply(lambda x: len(x.unique()))

# menIR_new.info()

IRIS                 49637
LIBCOM               33042
TYP_IRIS                 4
C16_PMEN_MENPSEUL    38760
C16_PMEN_MENSFAM     27023
C16_PMEN_MENFAM      40857
C16_PMEN_CS1         20045
C16_PMEN_CS2         34493
C16_PMEN_CS3         34603
C16_PMEN_CS4         38022
C16_PMEN_CS5         38158
C16_PMEN_CS6         38760
C16_PMEN_CS7         39622
C16_PMEN_CS8         29344
dtype: int64

In [16]:
menDetail_IR_new.apply(lambda x: len(x.unique()))

IRIS                    49637
LIBCOM                  33042
TYP_IRIS                    4
C16_PMEN_MENSFAM        27023
C16_PMEN_MENHSEUL       36983
C16_PMEN_MENFSEUL       37018
C16_PMEN_MENCOUPSENF    39193
C16_PMEN_MENCOUPAENF    40133
C16_PMEN_MENFAMMONO     35313
C16_PMEN_CS1            20045
C16_PMEN_CS2            34493
C16_PMEN_CS3            34603
C16_PMEN_CS4            38022
C16_PMEN_CS5            38158
C16_PMEN_CS6            38760
C16_PMEN_CS7            39622
C16_PMEN_CS8            29344
dtype: int64

In [17]:
# menIR_new.shape

### Checking missing values
No data are missing!

In [21]:
# menIR_new.isnull().sum()/len(menIR_new)*100
# menDetail_IR_new.isnull().sum()/len(menDetail_IR_new)*100

### Focus on IRIS Type inhabitant --> H

In [11]:
menIR_Wbase['TYP_IRIS'].unique()

array(['Z', 'H', 'A', 'D'], dtype=object)

Reminder:<br>
- IRIS d'habitat (H) : IRIS dont la population se situe entre 1 800 et 5 000 habitants ; ils sont homogènes quant au type d'habitat ;
- IRIS d'activité (A): IRIS regroupant plus de 1 000 salariés et comptent deux fois plus d'emplois salariés que de population résidente ;
- IRIS divers (D): IRIS de superficie importante à usage particulier (bois, parcs, zones portuaires...).
- IRIS autres (Z).

In [22]:
menIR_H_new = menIR_new[(menIR_new.values  == "H")]
menIR_H_new

,IRIS,LIBCOM,TYP_IRIS,C16_PMEN_MENPSEUL,C16_PMEN_MENSFAM,C16_PMEN_MENFAM,C16_PMEN_CS1,C16_PMEN_CS2,C16_PMEN_CS3,C16_PMEN_CS4,C16_PMEN_CS5,C16_PMEN_CS6,C16_PMEN_CS7,C16_PMEN_CS8
2,010040101,Ambérieu-en-Bugey,H,413.886432,16.982037,1122.237523,0.000000,41.819012,111.781115,316.435520,301.682610,327.623216,326.516622,127.247897
3,010040102,Ambérieu-en-Bugey,H,804.597713,62.677469,2678.934981,1.869824,110.283774,198.350309,651.851812,740.077839,1017.688131,583.688074,242.400400
4,010040201,Ambérieu-en-Bugey,H,797.117301,110.911917,3089.972506,0.000000,175.319668,434.218414,787.506170,725.234715,1038.894732,736.657488,100.170536
5,010040202,Ambérieu-en-Bugey,H,516.868664,65.990466,3925.814309,0.000000,289.409518,655.208954,1226.205531,722.669183,738.262085,818.095441,58.822726
32,010330101,Bellegarde-sur-Valserine,H,249.537370,30.643822,1132.319901,17.968042,28.617335,90.261176,213.305718,247.865657,481.204405,277.013657,56.265102
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49631,974230201,Les Trois-Bassins,H,72.412783,65.612562,623.163042,0.000000,40.295273,110.809324,109.618542,129.763490,207.903543,127.538501,35.259714
49632,974240101,Cilaos,H,237.651807,39.608635,1386.302208,9.902159,79.217269,123.776983,168.336697,430.743900,410.939583,202.994252,237.651807
49633,974240102,Cilaos,H,178.238855,99.021586,1356.595732,44.559714,89.119428,9.902159,79.217269,410.939583,495.107931,163.385617,341.624473
49634,974240103,Cilaos,H,99.021586,0.000000,608.982755,9.902159,29.706476,4.951079,69.315110,202.994252,217.847490,89.119428,84.168348
49635,974240104,Cilaos,H,94.070507,24.755397,891.194276,0.000000,103.972666,0.000000,0.000000,173.287776,519.863328,94.070507,118.825904

In [23]:
menDetail_IR_H_new = menDetail_IR_new[(menDetail_IR_new.values  == "H")]
menDetail_IR_H_new

,IRIS,LIBCOM,TYP_IRIS,C16_PMEN_MENSFAM,C16_PMEN_MENHSEUL,C16_PMEN_MENFSEUL,C16_PMEN_MENCOUPSENF,C16_PMEN_MENCOUPAENF,C16_PMEN_MENFAMMONO,C16_PMEN_CS1,C16_PMEN_CS2,C16_PMEN_CS3,C16_PMEN_CS4,C16_PMEN_CS5,C16_PMEN_CS6,C16_PMEN_CS7,C16_PMEN_CS8
2,010040101,Ambérieu-en-Bugey,H,16.982037,209.444911,204.441520,342.904766,644.624302,134.708455,0.000000,41.819012,111.781115,316.435520,301.682610,327.623216,326.516622,127.247897
3,010040102,Ambérieu-en-Bugey,H,62.677469,375.943227,428.654487,699.920557,1457.981108,521.033317,1.869824,110.283774,198.350309,651.851812,740.077839,1017.688131,583.688074,242.400400
4,010040201,Ambérieu-en-Bugey,H,110.911917,324.086045,473.031256,842.088176,1664.905434,582.978897,0.000000,175.319668,434.218414,787.506170,725.234715,1038.894732,736.657488,100.170536
5,010040202,Ambérieu-en-Bugey,H,65.990466,232.024615,284.844049,1245.799403,2202.893785,477.121121,0.000000,289.409518,655.208954,1226.205531,722.669183,738.262085,818.095441,58.822726
32,010330101,Bellegarde-sur-Valserine,H,30.643822,92.031565,157.505806,343.967296,662.436789,125.915816,17.968042,28.617335,90.261176,213.305718,247.865657,481.204405,277.013657,56.265102
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49631,974230201,Les Trois-Bassins,H,65.612562,51.723416,20.689367,81.663202,365.338145,176.161694,0.000000,40.295273,110.809324,109.618542,129.763490,207.903543,127.538501,35.259714
49632,974240101,Cilaos,H,39.608635,133.679141,103.972666,252.505045,752.564056,381.233107,9.902159,79.217269,123.776983,168.336697,430.743900,410.939583,202.994252,237.651807
49633,974240102,Cilaos,H,99.021586,89.119428,89.119428,198.043173,792.172690,366.379869,44.559714,89.119428,9.902159,79.217269,410.939583,495.107931,163.385617,341.624473
49634,974240103,Cilaos,H,0.000000,64.364031,34.657555,103.972666,351.526631,153.483459,9.902159,29.706476,4.951079,69.315110,202.994252,217.847490,89.119428,84.168348
49635,974240104,Cilaos,H,24.755397,49.510793,44.559714,113.874824,643.640311,133.679141,0.000000,103.972666,0.000000,0.000000,173.287776,519.863328,94.070507,118.825904

In [24]:
menIR_H_new.to_csv('IRIS_household/IRIS_household_IR_Hab.csv')

In [26]:
menDetail_IR_H_new.to_csv('IRIS_household/IRIS_household_detailed_IR_Hab.csv')